name: flutter_winnerapp_website
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  get: 4.6.5
  flutter:
    sdk: flutter
  appwrite: ^11.0.0
  get_storage: ^2.1.1
  darty_json_safe: ^1.0.2
  flutter_smart_dialog: ^4.9.5+1
  shared_preferences: ^2.2.2
  markdown_toolbar: ^0.5.0
  markdown_widget: 2.2.0
  fluent_ui: ^4.7.7
  logger: ^2.0.2+1
  random_x: ^0.3.1
  extended_image: ^8.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/
